### ISSUE TITLE
Please add Pinyin characters support

### ISSUE THREAD

**Issue by zhangyuesai** [damienleroy/PowerAccent#10]
Thanks for this awesome tool! I wonder if _Pinyin_ support can be added.

_Pinyin_ is a romanization system for Mandarin Chinese. There are 6 letters (A, E, I, O, U, Ü), together with their lowercase forms (a, e, i, o, u, ü). Each letter has four tones ( ̄ ́  ̌  ̀ ), so there are 6 * 2 * 4 = 48 accented characters in total. A detailed list of all accented characters with their Unicode can be found at [https://en.wikipedia.org/wiki/Pinyin#Unicode_code_points](https://en.wikipedia.org/wiki/Pinyin#Unicode_code_points).

The **Rare letters** are rarely used and the **Shorthand pinyin letters** are never used in practice. So only the **Common letters** section is needed.

**Comment by NightFurySL2001** [comment]
Even though **rare letters** are "rare", they are still required to correctly type *pinyin* for Mandarin Chinese. E.g. 嗯 is officially transcribed as ňg/ǹg, 呣 has an additional sound of m̀ in 现代汉语词典, and 额 é vs 诶 ế should be differentiated.

Also, m/n series of pinyin alphabets are used in [Tâi-Lô](https://en.m.wikipedia.org/wiki/T%C3%A2i-u%C3%A2n_L%C3%B4-m%C3%A1-j%C4%AB_Phing-im_Hong-%C3%A0n) and [Pe̍h-ōh-jī](https://en.m.wikipedia.org/wiki/Pe%CC%8Dh-%C5%8De-j%C4%AB) for Hokkien which are still in use in Taiwan, so it'll be a great idea to also support those two alongside Mandarin pinyin.

**Comment by damienleroy** [comment]
It is a lot to take account.
I plan a release with the possibility to choose the country.
But I guess I will have a lot of questions as I don't the subtilite of these languages. Will try to include that I will come back if I have some questions.

**Comment by zhangyuesai** [comment]
Thank you for considering this! I wil be glad to be of help if you have any questions.

BTW, rather than an accented variation of U, letter Ü is considered as an independent letter in _pinyin_. In most pinyin input methods, you press V to input Ü. So it would be more reasonable to consider Ü as a variation of V (in the context of _pinyin_).

**Comment by damienleroy** [comment]
So, about what I understood, here how it will look like:
![image](https://user-images.githubusercontent.com/13002713/189436455-b03b1117-65ff-4473-aea5-05253e5e8743.png)
And for the different variation of the U & Ü, the default order I am proposing:
![image](https://user-images.githubusercontent.com/13002713/189436539-5f57d793-5aae-47db-9fc8-92e3a8f5879a.png)

Is it seems good for you?

**Comment by damienleroy** [comment]
I could just added the one gave by @zhangyuesai , the others are not compatible with the current way how PowerAccent work.
`n̄` for example is made with two characters. So That mean, I will need to involve the tool on this way to make it works. It's so a long term issue.

**Comment by damienleroy** [comment]
Oh, sorry, just read again everything, and you talked about stroke V to get `ü`.
So here we go for U:
![image](https://user-images.githubusercontent.com/13002713/189439082-1df75610-6b4d-45af-9d22-073ef5d04338.png)
And for V:
![image](https://user-images.githubusercontent.com/13002713/189439115-3e4d0ddf-df04-4590-9483-73de13e6ff2c.png)

**Comment by damienleroy** [comment]
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0
Don't hesitate to create an another issue if you notice something wrong

**Comment by zhangyuesai** [comment]
Looks good to me! Thank you so much! _Xièxie_!
