### ISSUE TITLE
Please add Spanish ñ, Ñ

### ISSUE THREAD

**Issue by gustavorlopez** [damienleroy/PowerAccent#12]
Hi, your PowerAccent is great ! Could you add spanish char **ñ / Ñ** ?
This letter is found on the Spanish keyboard on the key **;**

**Comment by gustavorlopez** [comment]
Excellent !

**Comment by damienleroy** [comment]
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0
