### ISSUE TITLE
Select multiple character sets (instead of just single one or all of them)

### ISSUE THREAD

**Issue by thebro** [damienleroy/PowerAccent#122]
I use EN-US keyboard (and keyboard layout) but I often type in few additional languages (e.g. Swedish and Serbian).

I would prefer to see only Swedish and Serbian accents in the toolbar instead of having to see all possible accents for all other languages that I do not use.

So it would be nice to be able to select multiple languages when choosing a character set in settings.

**Comment by BConsult** [comment]
Yess!
Also useful for me to use Italian and German.
A customizable SET of characters could also come in handy as an alternative.

**Comment by ArR4e** [comment]
I also vote for this feature

**Comment by flaruggi** [comment]
It could be very useful to choose different multiple sets.

**Comment by cuzer** [comment]
Voting yes please! I'm multilingual, and I need to switch between 3 languages frequently. Would be great to be able to select multiple character sets instead of only one.

**Comment by damienleroy** [comment]
Hello, sorry for the delay..
Is someone can check about this release please and up if something going wrong?
https://github.com/damienleroy/PowerAccent/releases/download/2.0.2-beta/PowerAccent.msi

A lot of demands was about this feature and so here is it now!

You can select any languages as you want (except for the first one which is ALL languages).
Thanks for your return.

Just please now it is on beta until it has been validated by some.

**Comment by thebro** [comment]
Thank you very much for working on providing this feature for us!

Note: I used the software through QuickAccent (part of PowerToys) so far, so this is my first usage of PowerAccent UI.

The multiple character sets is looking good. I've tried to select two or three "countries".

![image](https://github.com/damienleroy/PowerAccent/assets/3052522/5f053cc3-08e8-4f0f-9661-89743b00c751)

But I have issues with the theme, I do not see some buttons and text in options (I have Win 11). It was hard for me to figure out how to apply character sort order as buttons are not visible. Once I clicked the right invisible button, sort order got applied properly.
Maybe this is some known unrelated issue, I haven't tried other versions of PowerAccent yet.
There was also one freeze when I couldn't select the "Options" tab, but I could others. And I closed the window but after that I couldn't get the menu when I right-clicked the icon in system tray. (It may be related to having open the PowerToys in the meantime so I could disable QuickAccent there.)
![image](https://github.com/damienleroy/PowerAccent/assets/3052522/70c131ed-7406-44de-86b1-73835c8612f0)
![image](https://github.com/damienleroy/PowerAccent/assets/3052522/468cd1c7-3ba3-406e-a678-6a4dbb8e1581)

**Comment by damienleroy** [comment]
Thanks for the return. Will try to check that asap.

**Comment by brionyryles** [comment]
Similarly, thank you for adding this feature, which is going to be really helpful for me. I have the same observations as thebro, with an addition that although my hotkey is left/right arrows, I'm triggering PowerAccent while navigating through a Word document using Ctrl + left/right. This brings up an option usually for e, or occasionally a or E. I'm not able to select a letter in this way, however and it appears frozen. The selction box eventually disappears after several more Ctrl+L/R presses. I also have QuickAccent installed via PowerToys, although it is PowerAccent that is creating the dialogues as characters from my two selected languages are present.

**Comment by damienleroy** [comment]
Hello, thank you for the feedback.
In this release: https://github.com/damienleroy/PowerAccent/releases/tag/2.0.2
The display issue has been fixed (this is related to the Windows dark theme, now it displays in a dark color as it should) and I have merged the changes about multiple selections.

Please note, unfortunately, I will not be able to make the changes to QuickAccent (PowerToys) right now. I will need to adapt some things before making it compatible.
