### ISSUE TITLE
Premade jobe for further accent-letters

### ISSUE THREAD

**Issue by toraxmalu** [damienleroy/PowerAccent#17]
Hi,
I extracted the accent-letters I cad and transformed them in code, so far I found the connection points.

Because I am totaly clueless with C# I beg your pardon, if there is a mistake and I a totally aware of the uncompleteness of the source code.

Cheers.
[KeyEnum.cs and SettingsService.cs.zip](https://github.com/damienleroy/PowerAccent/files/9530289/KeyEnum.cs.and.SettingsService.cs.zip)

**Comment by damienleroy** [comment]
Hello, thanks for your help :)

I've got something like that in my mind. But I need to finish something else first before considerate it. But be sure I will use it.

**Comment by damienleroy** [comment]
Implemented what you did for the next release:
https://github.com/damienleroy/PowerAccent/pull/15/files#diff-b11ad4dc358201859eb322e8e7383f60fd7ab2c2f9b29a833d4934ae18e493f3R34

Whith small differences. I removed keys for Minus/Plus/Equal, depending of the keyboard it is not possible to use them. So I moved the characters in the comma key for now, waiting for a better idea.

**Comment by damienleroy** [comment]
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0
