### ISSUE TITLE
Support for Māori macrons

### ISSUE THREAD

**Issue by nullpainter** [damienleroy/PowerAccent#19]
The Māori language is one of the three official languages of New Zealand. It would be great if the Māori  ā ē ī ō ū macronised vowels were supported.

**Comment by damienleroy** [comment]
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0

**Comment by nullpainter** [comment]
Thanks! I haven't pulled the code yet, but I'm not sure what this is doing in `GetDefaultLetterKeyMI()`. The only accented characters in Māori are vowels.

```c#
case LetterKey.S:
  return new char[] { '$' };

**Comment by damienleroy** [comment]
Indeed, but I also readed on Wikipedia Māori are using dollars as currency. So I thought it was not so much to adding it.
