### ISSUE TITLE
Math option

### ISSUE THREAD

**Issue by damienleroy** [damienleroy/PowerAccent#23]
https://github.com/damienleroy/PowerAccent/pull/15#issuecomment-1240726151
>Heh... even English has a few math symbols/em dashes/archaic accents that are unrepresented... æ œ – (em dash, I think...?) - (normal dash) ⁸ (superscript numbers) ½ (fractions) ≠≈ ø × √ ÷ (math symbols, perhaps on number keys?) ⁑ ⁂ ★ § ‼ ‽ † ‡ ※ (typography/writing), α β γ (Greek letters) ... I added a bunch in SymWin, back in the day.
>Idea: a "Maths" flag that can be checked for math symbols, English flag for archaic British English characters, a "Writers" flag for typography characters like dashes, daggers/asterisks

**Comment by Jay-o-Way** [comment]
This would basically mean a copy of the text/characters section of the Emoji Input Panel... 🤔

**Comment by damienleroy** [comment]
After several time, I can say mathematical symbol will not be implemented in PowerAccent (for now).
Here the reasons:
- There is a debat between keep only accents and keep tool simple to his usage, or activate this kind of feature, but with the risk to create a truly labyrinthine system.
- Implement so much symbol will be a problem, each keyboard have is own symbol location, and sometimes in concurrency with others symbols (ex: `5` and `(` is the same key in FR layout, so it is not possible to give 2 differents action to this key, or too much complex, as it demand to create a specific case for each existing keyboard layout).

It is not closed to make it evolve later, depending also of how PowerAccent will evolve himself, but currently it's a no go.
