### ISSUE TITLE
Suggestion: adding an option to automate the space after the modification

### ISSUE THREAD

**Issue by alecaselli** [damienleroy/PowerAccent#28]
I don't know if this happens in other languages but in italian the accent is very often (if not always) put at the end of a word, so would be incredibly optimizing to add an option that allows the program to put a space after the modification of the selected character

**Comment by damienleroy** [comment]
Indeed, could be. We will add that :)

**Comment by damienleroy** [comment]
Option added to the last release:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.1
