### ISSUE TITLE
Support for Indic diacritics in English (India)

### ISSUE THREAD

**Issue by alphayama** [damienleroy/PowerAccent#31]
I wanted to know if I can contribute to the project by adding support for Indic Diacritics in English (India) in the project.

**Comment by damienleroy** [comment]
Yeah sure. Don't hesitate to create a PR and propose it. That was already done by the past.
If you are not sure about coding part, you can also make your proposal there, and I will implement the characters myself :)

**Comment by damienleroy** [comment]
Can you give me some "source data" to your interested "desirable result output"?
About what I understood there is not accent when you are using English for india language.

**Comment by alphayama** [comment]
Yes, it is true that Indian English normally doesn't use accents/diacritics. However, they are used in some specific cases especially in academia where they are used to accurately transliterate (not translate) various words from Indian languages to Latin script. If this use case is unacceptable, feel free to close this issue and I will not request for this feature in the future.

Also, I haven't created a PR yet as I was busy and had some health issues. I have to start working on it.

**Comment by Jay-o-Way** [comment]
@alphayama do you have a few examples?

**Comment by alphayama** [comment]
Yes, I can give two examples:
1. [A Wikipedia article about ancient philologist and linguist Pāṇini](https://en.wikipedia.org/wiki/P%C4%81%E1%B9%87ini). The article uses IAST to transliterate names and excerpts from his works (originally in Sanskrit).
2. [Chapter 3: Algorithms by Jeff Erickson](https://jeffe.cs.illinois.edu/teaching/algorithms/book/03-dynprog.pdf). The Sanskrit terms and names in the first section of the chapter and some footnotes in some pages use IAST for transliteration

It is not normally used by people but people in academia and who are interested in topics like Indian history, religion etc. like to use IAST when writing articles or posts.

**Comment by damienleroy** [comment]
So, If I understood well, you are talking about this characters ?
```
āīñśū
```
Don't hesitate to tell me if there is missing character or if I am wrong

**Comment by damienleroy** [comment]
I may have something. Can you confirm this list is related about what you want?
https://en.wikipedia.org/wiki/ISO_15919

**Comment by alphayama** [comment]
Yes.
