### ISSUE TITLE
Request for more Money Symbols

### ISSUE THREAD

**Issue by Aegim** [damienleroy/PowerAccent#32]
Being able to type € with PowerAccents is wonderful! Would it be possible to add Korean Won (₩), Chinese Yuan (¥), Indian Rupee (₹), Philippine Peso (₱), Swiss Franc (₣), British Pound (£), Turkish Lira (₺), & Russian Ruble (₽) to PowerAccents? Sorry if I got any symbols wrong.

**Comment by damienleroy** [comment]
Hello, If you install the last update you have a currency section. Please try it and let me know.

**Comment by Aegim** [comment]
Thank you! I currently have PowerToys running, but I should have checked first.

**Comment by damienleroy** [comment]
We are working to bring the same feature to PowerToys.
Have fun!
