### ISSUE TITLE
Add Language Option for new Sorting

### ISSUE THREAD

**Issue by Blaxzter** [damienleroy/PowerAccent#33]
Thank you for your Tool.

My enhancement / feature request is regarding the sorting of the symbols.
Pressing space multiple times to get to the symbol i need most is a bit tedious.
By using this data per capita [Relative frequencies of letters in other languages](https://en.wikipedia.org/wiki/Letter_frequency#Relative_frequencies_of_letters_in_other_languages) one could easily increase the usability of this tool.

The specific feature request would be: Adding an option in the settings with a dropdown that contains the supported languages, which resorts the toolbar options. 

As a German, I need ë, ö, ü quite often, which seems to be unusual internationally. 
Now I have to wait till the toolbar appears and press the button 2 – 3 times.
With this improvement I wouldn't need to wait because for my country the ones I require most appear first.

**Comment by damienleroy** [comment]
Hello,
Is it something I need to improve indeed.
In the mean time you have already the option to move by yourself the positions of the characters in the settings.
![image](https://user-images.githubusercontent.com/13002713/190409733-5020c30f-9fdf-4fa2-a689-05f1ff7ad8df.png)

**Comment by Blaxzter** [comment]
Is that window accessible in the version deployed in Power Toys?

**Comment by damienleroy** [comment]
No unfortunaly. On PowerToys the decision was taken to use their own interface. So it ask to be implemented PowerToys side too.
For now this feature is only available in PowerAccent.

**Comment by damienleroy** [comment]
I invite you to create an issue PowerToys side. We will be able may be to work on it soon.
