### ISSUE TITLE
Turkish ' I ' / ' i ' character variations are missing

### ISSUE THREAD

**Issue by alpturedi** [damienleroy/PowerAccent#38]
Turkish language option works fine with one small mistake and one big mistake right now.

1.  Turkish "I" character is weird. There are two distinct characters using the English I glyph that is `I ı` &  `İ i `So we need:
- For regluar i key (lowercase i): `ı`  U+0131 added at the first place
- For capitalized I key (shift + i OR caps lock i): `I` U+0130	 added at the first place

2. Second issue is rather small:
- For some reason Spanish `ñ` is the top of the list for the key "u", it needs to be `ü` for regular Turkish use

**Comment by alpturedi** [comment]
https://github.com/alpturedi/PowerAccent/commit/79679e04d39abaecb7c41be2806ea059fd391555#diff-b11ad4dc358201859eb322e8e7383f60fd7ab2c2f9b29a833d4934ae18e493f3

This should be the letter list for the Turkish IMO. We don't have ï double dot accents so I removed them as well and fixed the ordering.

**Comment by alpturedi** [comment]
This is solved with this PR
https://github.com/damienleroy/PowerAccent/pull/39

**Comment by damienleroy** [comment]
Indeed. I even don't know why I've got so far in the Turkish accents (I'm not Turkey but Wikipedia don't showing them). Anyway thanks to cleaning all of this. It is really helpfull :)
