### ISSUE TITLE
Turkish characters support!

### ISSUE THREAD

**Issue by yucelyilmazvfx** [damienleroy/PowerAccent#4]
This is a great utility. I use it with my British keyboard. Only missing character for Turkish is "Ş" or "ş". If you can add these characters to "S" or "s" it will be compatible with Turkish alphabet. Thanks in advance.

**Comment by damienleroy** [comment]
Hello, thanks :)
Is this "ş" is the only Turkish character you are using there?
I plan to add settings by country. So I can add all Turkish characters in the same time.

**Comment by yucelyilmazvfx** [comment]
Thanks for replying back. Here is the all Turkish characters.
I hope it helps. 

ğ, Ğ, ç, Ç, ş, Ş, ü, Ü, ö, Ö, ı, İ

**Comment by damienleroy** [comment]
Thank you! good to know. I will integrate them and let you know when the release is done :)

**Comment by yucelyilmazvfx** [comment]
I appreciate it. Thank you very much

**Comment by damienleroy** [comment]
Development still ongoing. For now it will look like that:
![image](https://user-images.githubusercontent.com/13002713/188937463-405011f5-e723-4985-aac7-c8bbb08092fe.png)

You will be able to choose the country, (here Turkish alphabet is selected), more will come for the next release.

**Comment by yucelyilmazvfx** [comment]
Wow it looks great. I believe your app is now integrated with Powertoys if i am not wrong.

**Comment by damienleroy** [comment]
Yes, release of PowerToys is live, an the tool in known in Powertoys as "Quick Accent".

**Comment by damienleroy** [comment]
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0
