### ISSUE TITLE
Request for 'input delay' option

### ISSUE THREAD

**Issue by Capone2412** [damienleroy/PowerAccent#41]
Can you add an 'input delay' option, please?
I recently switched from the PowerToys version and that's a point I sorely miss.

---

One thing I noticed: If you select 'world wide' as country, you don't have access to the German 'ß'.

**Comment by damienleroy** [comment]
Thanks for the feedback.
For the german `ß` it as already been fix, but not release yet. So it will be ok for the next version.

**Comment by damienleroy** [comment]
All done!
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.2

**Comment by Capone2412** [comment]
You're gorgeous. Thank you very much for the quick implementation of the 'input delay' option.

Apparently you sorted the German 'ß' under the letter 'B' for the 'world wide'-country, but it should be under 's'. :)

**Comment by damienleroy** [comment]
Hello, thank you for the ☕ :)
Indeed, it already up on my side, and fixed. Will be ok for the next release.
