### ISSUE TITLE
Since ß makes an S sound, can it be moved to S and not stay in B?

### ISSUE THREAD

**Issue by Aegim** [damienleroy/PowerAccent#42]
ß is in B, instead of S where it would be expected. Could that be altered in a later update?

Best regards!

**Comment by Jay-o-Way** [comment]
Omg who placed it under the B in the first place?

**Comment by damienleroy** [comment]
My bad. Issue only in ALL option. Fixed that, it will be ok in the next release.

**Comment by damienleroy** [comment]
Fixed in PowerAccent:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.3
