### ISSUE TITLE
Create docs for goals

### ISSUE THREAD

**Issue by Jay-o-Way** [damienleroy/PowerAccent#44]
Much needed, but still missing: a doc with goals and non-goals, including their priority.
It's absolutely critical to set boundaries, or this app could grow uncontrollably in result to people wanting more and more different things.

**Comment by damienleroy** [comment]
I agree. The thing is, I don't know myself where to set the boundaries of the app.
But after a long brainstorming, you are right. And it could be greaţ to limit it to Latin characters. Which means I should remove greek language..
To write with different characters, some other tools are more capable than PA.
Thanks to up this question. I will update the README.md.
