### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by Jay-o-Way** [damienleroy/PowerAccent#45]
Like

- [ ] Changelog
- [ ] Info 'bout recent adoption by PowerToys (will this repo stop or be a redundant copy or..?)
- [ ] etc.

**Comment by damienleroy** [comment]
Added a `PowerToys` section in the README:
https://github.com/damienleroy/PowerAccent/pull/49/files
Is it clear enough?

I removed CHANGELOG file. Currently the changes are resume in the release page.
It could be better in the future to add a real changelog file, but it is not my priority for now.

**Comment by Jay-o-Way** [comment]
> Added a `PowerToys` section in the README:
> https://github.com/damienleroy/PowerAccent/pull/49/files
> Is it clear enough?

Does that mean both "versions" will continue to exist (read: be maintained) for a while?
A link would be nice.

**Comment by damienleroy** [comment]
Yeah. For now I want to maintain PowerAccent. Several reasons for that:
- Having my own repo with my 'own' tool. This is better for my experiences with github and for professional visibility.
- For now it's ok, but it is possible one day PowerToys team want have an another direction to take with the tool.
- Let the choice to people to have the feature without installing PowerToys if they not want to.

In the beginning I proposed to keep this repo as reference for the integration in PowerToys, for some reasons (which I can understand) it was decided to 'copy/paste' what have been done and create an another version of it.
But in any case I am not ready to forget this one :)
