### ISSUE TITLE
Doesn't seem to activate for the letter "r".

### ISSUE THREAD

**Issue by andrewschmidgit** [damienleroy/PowerAccent#48]
Not sure how many languages have an accent for the letter r, but Czech has the "ř" letter

**Comment by damienleroy** [comment]
It is working on my side. Which version are you using? Is it working for all other Czech special letters?
![image](https://user-images.githubusercontent.com/13002713/192381586-efedc19d-f192-4110-8f46-d89d077cc149.png)

**Comment by andrewschmidgit** [comment]
I am on PowerToys version v0.62.1
It seems to be working for other letters with háčky (typed with PowerAccent)
