### ISSUE TITLE
Trouble activating in PowerTools

### ISSUE THREAD

**Issue by k3davis** [damienleroy/PowerAccent#5]
I could use this utility (and received it via the PowerToys update), but I am not smart enough to activate it. 🙃

When I have the tool enabled, and follow the example given (press and hold `e` then hit `space`), I end up with a bunch of e's and spaces.... as I would expect.

I tried changing the "Activation key" from 'Both' to 'Space' but it isn't saved (when I navigate away and come back, the setting is still 'Both').

**Comment by dziban303** [comment]
I also have trouble. The way I can get it to (sort of) work is to very precisely hit the letter key and the activation key simultaneously. 

Note that in my testing so far, the overlay that's supposed to appear for selecting from multiple diacritics does not appear while typing in Discord, which is catastrophic for my use case as that's where I'd write 75% of the diacritics.

**Comment by damienleroy** [comment]
Hello!

@k3davis indeed, you need to push both keys at the same time to make it works. If it don't work, may be something was wrong on the execution of the tool. But I will need more information about that (be sure also it was activated in PowerToys, it can be deactivate by default).

@dziban303 some tests has been done for managing second monitor, but need to be tested more. We will try to get more test, and this with Discord to be sure.

**Comment by k3davis** [comment]
@domepida Interesting observation. I ended up disabling this tool because I could never once get it to trigger, but I am indeed using a bluetooth keyboard (on a desktop, in my case). I didn't think that might be related.

**Comment by damienleroy** [comment]
Ok, thanks for the feedback. I will need to find a Bluetooth keyboard to test the issue :)

**Comment by domepida** [comment]
I tried the 0.62.1, and it works for me now. Not sure what have you done, but it works on both keyboards 👯

**Comment by k3davis** [comment]
It works for me now also on powertoys 0.62.1. Maybe it was a conflict with the Keyboard Manager or some other tool that was the real culprit, idk. Thanks!
