### ISSUE TITLE
enhancement: letters for HU=Hungarian

### ISSUE THREAD

**Issue by freaxnx01** [damienleroy/PowerAccent#50]
Thank your for the nice and practical piece of software.
May I propose to add letters for hungarian language?

Ő ő Ű ű

see https://www.wikiwand.com/de/Ungarische_Sprache

Thank you in advance.

Best regards
Andreas

**Comment by damienleroy** [comment]
Hello,
Thanks for the proposition. It will be integrate for the next release.

**Comment by damienleroy** [comment]
New release :
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.3
