### ISSUE TITLE
causes UX issues for videogames if space is used.

### ISSUE THREAD

**Issue by user4302** [damienleroy/PowerAccent#51]
lets say im moving in a fullscreen game (w, a, s, d), and hit space ,
the game minimizes.

so, maybe add an option to disable this app for fullscreen apps, or maybe for certain apps.
for now, switching to the arrow keys instead of space seems to be the best option.

**Comment by damienleroy** [comment]
Hello, Last version of PowerAccent contain an option for that.
However on PowerToys it is not the case yet. But a development is still ongoing.
