### ISSUE TITLE
Accents for Dutch are incomplete

### ISSUE THREAD

**Issue by ftamminga** [damienleroy/PowerAccent#56]
The accents set for the Dutch language is incomplete. We use a some accents on vowels. 

Please add:

ë é è ê
ä á 
ö ó ô
ï í 
ü ú

**Comment by rubenprins** [comment]
Also, the following accents are used in the official word list (woordenlijst.org):

à
ç (reçu)
î (maître)
ñ (piñata)
û (coûte que coûte)

So, basically
```csharp
switch (letter)
{
    case LetterKey.A:
        return new char[] { 'á', 'à', 'ä' };
    case LetterKey.C:
        return new char[] { 'ç' };
    case LetterKey.E:
        return new char[] { 'é', 'è', 'ë', 'ê', '€' };
    case LetterKey.I:
        return new char[] { 'í', 'ï', 'î' };
    case LetterKey.O:
        return new char[] { 'ó', 'ö', 'ô' };
    case LetterKey.U:
        return new char[] { 'ú', 'ü', 'û' };
}
```

**Comment by Jay-o-Way** [comment]
Yeah, I don't think I really agree. Dutch doesn't use many accents and the example words (like reçu, piñata) are clearly anything but Dutch.

**Comment by damienleroy** [comment]
In fact, I agree, the examples are not great. But tonight someone confirm me it is happenning. So I just added Dutch (Netherlands) at the side of German in PowerAccent.
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.3

It is something we could do in PowerToys, having Netherlands & German instead of Dutch. What so you think?

**Comment by Jay-o-Way** [comment]
I'm just sharing my opinion. Rule number 38: Your case, your lead :)

**Comment by damienleroy** [comment]
I prefer to have it. You making an interesting point. So it is not simple. I am still trying to understand.

https://en.wikipedia.org/wiki/Dutch_orthography
About what I can see in Netherlands for example there is the two langages. Dutch, which use also by Germans, but also French accents, which use in many situations. Like French words, or even Netherlands brands (like Eén).

Tell me if I am wrong. If it is the case I will remove them.
Meanwhile, here in PowerAccent I think for now it is better to have the possibility to have both. And let see how it is going :).

**Comment by rubenprins** [comment]
It's true most of these accents are rarely used, but they all exist in the official corpora, like the [official word list](https://woordenlijst.org) by the Dutch Language Union (Taalunie).

Not sure it makes sense to merge German and Dutch, as German has different letters (Dutch and German orthography have little in common). For example, ß doesn't occur in Dutch, and ë doesn't occur in German, AFAIK.

Also, "Netherlands" would be kinda weird for Belgium and Surinam, where Dutch is also a national language.

**Comment by Jay-o-Way** [comment]
True, "Dutch" is the language, "Netherlands" is the country. And yes, Dutch _does_ have accents, but not very many. I'll let it rest now 🤐
