### ISSUE TITLE
Please add Swedish to PowerAccent / QuickAccent

### ISSUE THREAD

**Issue by dbacker8** [damienleroy/PowerAccent#58]
Swedish characters: Å å Ä ä Ö ö
Thanks!
--dbacker8

**Comment by damienleroy** [comment]
Added:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.3
Have fun!

**Comment by dbacker8** [comment]
WOW!  Was that ever fast!!
Thank you!
--CB
