### ISSUE TITLE
More currency signs (Р→₽, Y→¥)

### ISSUE THREAD

**Issue by VladWinner** [damienleroy/PowerAccent#6]
Hello! PowerAccent already has this option:
![image](https://user-images.githubusercontent.com/13555921/188729624-9cd070e1-aae4-45a6-a072-26ae2ca8ba2a.png)
How about the same option for other currency signs?
E.g. Ruble sign `₽` via Cyrillic `Р`

This is already used in (custom) Ilya Birman's Typography Layout (Russian) when calling AltGr+P (h), because it is intuitive and more convenient than AltGr+8 in current Win8+ keyboard layout.
![image](https://user-images.githubusercontent.com/13555921/188730213-cfa333de-6c01-4ab6-9f22-0fd1bd49f028.png)

Other example: Yen sign `¥` via Latin `Y`

**Comment by Adam-Kay** [comment]
#### Would `$` via `S` be appropriate here as well?

<details>
  <summary>Other currency ideas</summary>
  
- `¢` from `C`  (Euro/Dollar cents)
- `₱` from `P`  (Philippines Peso & Cuba Peso)
- `₹` from `R`  (India Rupee)
- `₩` from `W`  (Korea Won)

</details>

**Comment by damienleroy** [comment]
Hello, no problem. I am currently working to add different countries alphabet.

@Adam-Kay That's not a bad idea

**Comment by damienleroy** [comment]
Adding Currency option
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0
