### ISSUE TITLE
enhancement: letters for DE=german

### ISSUE THREAD

**Issue by andyATRO** [damienleroy/PowerAccent#60]
great that you did a new release.
works well with my romanian language, as i asked for by the other issue.
but: my mothertongue is german.
if someone works with an english/french/islandic/... system he may need full german letterset.
so:
may i propose to add the 4 non-english letters for german language?
here they are:

äöüß

https://en.wikipedia.org/wiki/German_language#Orthography

thank you in advance.
regards, andy

**Comment by damienleroy** [comment]
Hello, Which version are you using? German is already implemented and propose the characters you are proposing from a previous version.

**Comment by damienleroy** [comment]
Hello, no problem. Sorry I still trying to understand.

So PowerToys v0.63.0 have an issue, which `Dutch` as a `German` behavior. So it should be rename as `German` for the next release.
https://github.com/microsoft/PowerToys/issues/20996

Second, sorry I don't understand when you are saying `because i am working on an austrian=german language system`. Can you please explain that?

**Comment by andyATRO** [comment]
hello again,
(sorry for late answer)
somewhere at the WINDOWS installations process or start of system you are asked to define your system language and country:
https://support.microsoft.com/worldwide
(this is not the exact page for this question at system installation/start but similar)
after this you have defined country, language and then used keyboard of your system. this is visible by some code inside brackets looking like (xx-yy).

examples:
1- i am sitting at an system in austria with german language and keyboard showing (de-at)
 2- an us-guy might sit at us-system with english language and his usual keyboard (en-us)
3- an english man will be characterized by (en-gb)
4- an canadien by (en-ca)

to 1- as long as is just use german language only i am fine. but when i need to write some romanian words i will use PowerAccent to write original romanian letters (not on austrian/german keyboards) ăâîșț
to 4- if an canadian wants to write german words he may want to use PowerAccent to be able to write äöüß

sorry for this lengthy description. now at midnight i may get complicated to explain.....

so, to answer your questions:
question 2:  answered above (i hope).
question 1:  no, everything is fine. the dutch language uses the 26 latin (=english) letters only. german uses 26 latin and the additional 4 letters, i talked....

ok, sorry, i hope you dont feel mad by such explanation (i just tried to be selected to next Nobel Price - *JOKE*).
regards, andy

**Comment by damienleroy** [comment]
Hello, I came back!

So the tool is not related to the choosen layout in Windows. Whenever the language, the OS... 

The please confirm it, if I understand well you want to change the PowerAccent language when the layout is changed?
Also, I didn't checked this point but, if you install it and go to a different windows account, you may be able to select a different configuration.

**Comment by andyATRO** [comment]
hello,
thanks for your question. this will clear up my confusing last post.....
NO, i dont want a change of P.A. language when windows/sytem language/layout is changed.
independent of country and system language/layout and independent of keyboard-layout
(e.g. france, belgium, germany and US use different keyboards)
P.A. will just react on the selected language inside PA - a fine solution.
i do hope i made my point clear......
and YES, different accounts will/can have different settings.
i tested even multiple PA languages (consecutive used at same account) works well. 
thank you very much.

**Comment by damienleroy** [comment]
Ok, so everything is ok! :)
And thanks a lot for all theses explanations.
Which you the best
