### ISSUE TITLE
Not an issue, but could we go lower than 100ms?

### ISSUE THREAD

**Issue by Oeoeo23** [damienleroy/PowerAccent#61]
Apologies in advance if I'm using bad GitHub protocol here...I'm as new and as noob as they come, and I'm not in tech at all

Anyway, any chance we could set the speed to below 100ms? I'm absolutely certain my keystrokes aren't even close to théfastest around (did you see that?) but 100ms is still giving me 1 or 2 unintentional accent insertions every time I'm typing something.

50ms? 25ms? 20ms? I'm sure there's some realistic floor to that speed, but as I'm finding out, 100ms is just too much space.

Thank you for théawesome PowerToy (again, you see that right?) Also thénew (:p) 'Set Language' option from v0.63.0 is very welcome!

**Comment by damienleroy** [comment]
Hello, since 200 ms has been implemented in the tool, and since the last release it propose to be modified as you wish:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.2

**Comment by damienleroy** [comment]
Just notice you are talking about PowerToys, it is the same:
![image](https://user-images.githubusercontent.com/13002713/194159388-f5555d4b-287e-4dde-83a6-844e179cd5f8.png)
