### ISSUE TITLE
Accented characters for Croatian language

### ISSUE THREAD

**Issue by mihaelbabic** [damienleroy/PowerAccent#63]
Only: č, ć, đ, š, ž

**Comment by sugar-king** [comment]
I am willing to add this - [related proposal on PowerToys](https://github.com/microsoft/PowerToys/issues/21358)

**Comment by damienleroy** [comment]
Done: https://github.com/damienleroy/PowerAccent/releases/tag/1.3.4

**Comment by mihaelbabic** [comment]
Thank You!
