### ISSUE TITLE
Open the panel on long key press instead of key-combo

### ISSUE THREAD

**Issue by JackNUMBER** [damienleroy/PowerAccent#64]
**What is your problem**
Using the tool need to be quick and learn an other key-combo.

**Describe the solution you'd like**
Is there anyway to open the panel on long key press? Instead of typing `eeeeeeeeee` when you press the `E` key for long time the PowerAccent could open, like mobile keyboard does.

**Comment by Darthagnon** [comment]
Related issue: #55

**Comment by damienleroy** [comment]
Duplicated yes. Thanks!
