### ISSUE TITLE
PowerAccent Portuguese

### ISSUE THREAD

**Issue by Giovannelm** [damienleroy/PowerAccent#69]
Hi Damien!

First of all, I'd like to thank you for creating PowerAccent, it helps me type on my english keyboard with portuguese accents and it has been a part of my daily life.

My request is to add a "Portuguese" language in the "choose language" category.

Thank you!

**Comment by effelle** [comment]
See [PR65](https://github.com/damienleroy/PowerAccent/pull/65). It should be available on next build.

**Comment by effelle** [comment]
Thanks. 
Please note there was already an implementation of PT under powertoys.
