### ISSUE TITLE
Polish 🇵🇱 Character Support

### ISSUE THREAD

**Issue by Adam-Kay** [damienleroy/PowerAccent#7]
Hello, I saw another issue about Turkish character support (#4), so wanted to provide a list of Polish letters for the eventual integration in the future:

### All Polish Accented characters:
- Ą ą
- Ć ć
- Ę ę
- Ł ł
- Ń ń
- Ó ó
- Ś ś
- Ź ź
- Ż ż

[[Source](https://en.wikipedia.org/wiki/Diacritic#Other_languages:~:text=Polish%20has%20the%20following%20letters)]

**Comment by damienleroy** [comment]
Hello. Indeed. So I will adding these polish characters for the next release.

Just know It's not good for user experience to have all existing characters in the same context. So you will be able to choose from which country you want the characters.

**Comment by damienleroy** [comment]
Release there:
https://github.com/damienleroy/PowerAccent/releases/tag/1.3.0
