### ISSUE TITLE
Additional special characters for Spanish

### ISSUE THREAD

**Issue by freddyfdeb** [damienleroy/PowerAccent#74]
In some keyboard distributions, e.g., Belgian AZERY, it is not possible to access Spanish special characters such as the opening question mark (¿) and the exclamation mark (¡).

I nice solution would be to add those characters to quick accent. The keys that can give access to those characters would be ? and !.

For example:

? + [Activation key] = ¿
! + [Activation key] = ¡

Btw, these symbols are accessible from the US International keyboard using

Right Alt + / = ¿
Right Alt + 1 = ¡

**Comment by damienleroy** [comment]
Hello, it is already ok for `¿` See here:
https://github.com/damienleroy/PowerAccent/blob/main/PowerAccent.Core/Languages.cs#L243
But you are right, I will add the `¡` later.
You can access it with `,` + `space`.

**Comment by freddyfdeb** [comment]
Thanks! Excellent work!

**Comment by damienleroy** [comment]
Added https://github.com/damienleroy/PowerAccent/releases/tag/1.3.4
