### ISSUE TITLE
Missing Polish characters

### ISSUE THREAD

**Issue by WrongBitDepth** [damienleroy/PowerAccent#76]
Hello

First I have to say that the plugin is fantastic and works amazingly. Great job!

The main reason for this issue is about missing Polish characters. I recently moved to the country and it is quite hard to type them.
Your software is a really good way to introduce them but they are not there.

`Ą, Ć, Ę, Ł, Ń, Ó, Ś, Ź, Ż`

**Comment by damienleroy** [comment]
Hello, sorry for the time. I just checked and they are there:
![image](https://user-images.githubusercontent.com/13002713/200611113-a2af48b4-fb7d-417d-8e31-6dd6096dc75c.png)
Note to get uppercase characters, you have to activate caps lock, or stroke shif key, as you do with usual character.

**Comment by damienleroy** [comment]
Or may be you can try with the last version. Polish as been added in version 1.3.0

**Comment by WrongBitDepth** [comment]
Thank you for your answer!
Yes! The latest update include them! That's a game-changer!
Congratulations on the app again.

**Comment by damienleroy** [comment]
Thank you! :)
