### ISSUE TITLE
Ability to set a primary Language

### ISSUE THREAD

**Issue by SoraTenshi** [damienleroy/PowerAccent#82]
**What is your problem**
I am currently embedding PowerAccent into my current workflow and noticed, that i would like to use German Umlauts for usual typing, but sometimes i would also like to have greek letters and currencies as a secondary option.

**Describe the solution you'd like**
An idea i just had would be to have some kind of priorisation of the language, to e.g. having all accents enabled allows you to set your primary language.

I don't know whether this has been thought about / needed by others, but i for sure would like that.

**Comment by damienleroy** [comment]
Hello, thank you for the feedback.
Unfortunately, PowerAccent is currently working with limited feature. And we can not implement everything we want, usualy for two reasons:
- We can not implement all characters for all countries in the world.
- Sometimes for technical reason. The way of the keyboards are working and the differents layout in the world can be quite complicated.
For theses reasons we decided to limit theses ones to romanian characters. Greek are not for example. Same for currencies or math symbols.

Therefore I am trying to find a global solution, like proposing each one using the tool to integrate the characters they want. But it still ask some works, and there is no garantee this will work.
