### ISSUE TITLE
Support for exclamation and question marks ¿¡

### ISSUE THREAD

**Issue by fabioroldan** [damienleroy/PowerAccent#89]
Thanks Damien, it is very useful 👍
To make it perfect, it would be necessary to add support for these characters: ¿ and ¡
shift + ! + (activation key) =  **¡**
shift + ? + (activation key) = **¿**

**Comment by damienleroy** [comment]
Hello. It is already supported with the comma `,` key when you are choosing Spanish (for example).

**Comment by fabioroldan** [comment]
It's good to know 👍, anyway I don't see support for "¡" and I think my proposal, although you have to combine three keys, is more intuitive. Perhaps you could add both shortcuts. 👋

**Comment by fabioroldan** [comment]
I just realized why you chose the comma for ¿, it's because of the French layout. I put a US layout ![https://upload.wikimedia.org/wikipedia/commons/4/4b/KB_United_States_Mac_-_Apple_Keyboard_%28MC184LL%29.svg](https://upload.wikimedia.org/wikipedia/commons/4/4b/KB_United_States_Mac_-_Apple_Keyboard_%28MC184LL%29.svg)
