### ISSUE TITLE
Arabic / Kurdish

### ISSUE THREAD

**Issue by OTM0202** [damienleroy/PowerAccent#90]
**What is your problem**
Some symbols that are used in Kurdish language and some Arabic accents are not available in the keyboard that can be added

**Describe the solution you'd like**
I don't have any experience in the coding languages, but I tried my best to mimic [Languages.cs](https://github.com/damienleroy/PowerAccent/blob/main/PowerAccent.Core/Languages.cs) and I wrote all the symbols that are needed in the Kurdish language and some Arabic accents:

`    //Arabic 
    private static char[] GetDefaultLetterKeyHR(LetterKey letter)
    {
        switch (letter)
        {
           
            case LetterKey.ا:
                return new char[] { 'أ', 'إ', 'آ', 'ٱ', 'ء', 'ئ', 'ى', 'الله' };
            case LetterKey.ب:
                return new char[] { 'پ' };
            case LetterKey.ج:
                return new char[] { 'چ' };
            case LetterKey.ر:
                return new char[] { 'ڕ' };
            case LetterKey.ز:
                return new char[] { 'ژ' };
            case LetterKey.ص:
                return new char[] { 'ﷺ' };
            case LetterKey.ف:
                return new char[] { 'ڤ' };
            case LetterKey.ك:
                return new char[] { 'گ', 'ﮐ' };
            case LetterKey.ل:
                return new char[] { 'ڵ' };
            case LetterKey.و:
                return new char[] { 'ۆ' };
            case LetterKey.ه:
                return new char[] { 'ھ' };
            case LetterKey.ي:
                return new char[] { 'ى', 'ێ' };
            case LetterKey.لا:
                return new char[] { 'لآ', 'لإ', 'لأ' };
            case LetterKey.0:
                return new char[] { '٠' };
            case LetterKey.1:
                return new char[] { '١' };
            case LetterKey.2:
                return new char[] { '٢' };
            case LetterKey.3:
                return new char[] { '٣' };
            case LetterKey.4:
                return new char[] { '٤' };
            case LetterKey.5:
                return new char[] { '٥' };
            case LetterKey.6:
                return new char[] { '٦' };
            case LetterKey.7:
                return new char[] { '٧' };
            case LetterKey.8:
                return new char[] { '٨' };
            case LetterKey.9:
                return new char[] { '٩' };
        }

        return Array.Empty<char>();
    }
`

**Comment by OTM0202** [comment]
I don't know if that is possible to add these languages. but if you can add theme it'll be nice. as many people who speak Kurdish have an issue with the keyboard...
Thank You

**Comment by damienleroy** [comment]
Hello, Thank you a lot for the feedback.
Unfortunaly as said in the [README](https://github.com/damienleroy/PowerAccent/blob/main/README.md) we are only supporting Latin base characters (for now).
We can't really implement all languages of the world, and also some technical reason limit some implementations. This is why this decision has been made.

Therefore this project have less than one year old. And there is a lot to be improve. So we are still thinking about a solution for that, but it is a long term plan.
